### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by beingentangled** [Taym95/flutter_clipboard_manager#1]
FlutterClipboardManagerPlugin.java:17: error: invalid method declaration; return type required
[   +1 ms]   private ClipboardManagerPlugin(Registrar registrar){
[        ]           ^
[  +72 ms] 1 error
[        ] FAILURE: Build failed with an exception.

**Comment by Taym95** [comment]
Thanks @beingentangled, fixed in #2.
